<#
.SYNOPSIS
Reports whether derived planning artifacts still match Mendix Epics stories.

.DESCRIPTION
Reads the generated Epics snapshot and Markdown frontmatter under planning. The
script never changes the board or derived artifacts; it writes a generated report.
#>

[CmdletBinding()]
param(
    [string]$SnapshotPath = (Join-Path (Split-Path -Parent $PSScriptRoot) 'sprints\generated\epics-snapshot.json'),
    [string]$PlanningDirectory = (Join-Path (Split-Path -Parent $PSScriptRoot) 'planning'),
    [string]$OutputPath = (Join-Path (Split-Path -Parent $PSScriptRoot) 'planning\generated\reconciliation-report.md')
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path -Path $SnapshotPath -PathType Leaf)) {
    throw "Snapshot '$SnapshotPath' does not exist. Run scripts/sync-epics-stories.ps1 first."
}

$snapshot = Get-Content -Path $SnapshotPath -Raw | ConvertFrom-Json
$storiesById = @{}
foreach ($story in @($snapshot.stories)) {
    $storiesById[$story.storyId] = $story
}

$artifacts = if (Test-Path -Path $PlanningDirectory -PathType Container) {
    Get-ChildItem -Path $PlanningDirectory -Recurse -File -Filter '*.md' |
        Where-Object { $_.FullName -notmatch '[\\/]generated[\\/]' -and $_.Name -ne 'README.md' }
} else {
    @()
}

$results = foreach ($artifact in $artifacts) {
    $content = Get-Content -Path $artifact.FullName -Raw
    $match = [regex]::Match($content, '(?s)^---\s*\r?\n(.*?)\r?\n---')
    if (-not $match.Success) {
        continue
    }

    $frontmatter = @{}
    foreach ($line in $match.Groups[1].Value -split '\r?\n') {
        if ($line -match '^\s*([^:#]+):\s*(.*?)\s*$') {
            $frontmatter[$matches[1].Trim()] = $matches[2].Trim().Trim('"', "'")
        }
    }

    $storyId = $frontmatter['board_story']
    $fingerprint = $frontmatter['source_fingerprint']
    if ([string]::IsNullOrWhiteSpace($storyId)) {
        continue
    } elseif ([string]::IsNullOrWhiteSpace($fingerprint)) {
        [PSCustomObject]@{ File = $artifact.FullName; Story = $storyId; Result = 'Review required'; Detail = 'Missing board_story or source_fingerprint.' }
    } elseif (-not $storiesById.ContainsKey($storyId)) {
        [PSCustomObject]@{ File = $artifact.FullName; Story = $storyId; Result = 'Review required'; Detail = 'Story is absent from the current board snapshot.' }
    } elseif ($storiesById[$storyId].sourceFingerprint -ne $fingerprint) {
        [PSCustomObject]@{ File = $artifact.FullName; Story = $storyId; Result = 'Review required'; Detail = 'Board story content changed since reconciliation.' }
    } else {
        [PSCustomObject]@{ File = $artifact.FullName; Story = $storyId; Result = 'Current'; Detail = 'Fingerprint matches current board story.' }
    }
}

$outputDirectory = Split-Path -Parent $OutputPath
New-Item -ItemType Directory -Force -Path $outputDirectory | Out-Null
$report = [System.Text.StringBuilder]::new()
[void]$report.AppendLine('<!-- Generated by scripts/reconcile-derived-artifacts.ps1. Do not edit manually. -->')
[void]$report.AppendLine('# Derived Artifact Reconciliation Report')
[void]$report.AppendLine()
[void]$report.AppendLine("Generated (UTC): $((Get-Date).ToUniversalTime().ToString('o'))")
[void]$report.AppendLine()
[void]$report.AppendLine('| Artifact | Board story | Result | Detail |')
[void]$report.AppendLine('|---|---|---|---|')
foreach ($result in @($results) | Sort-Object Story, File) {
    $relativeFile = [System.IO.Path]::GetRelativePath((Split-Path -Parent $PSScriptRoot), $result.File).Replace('\', '/')
    [void]$report.AppendLine("| $relativeFile | $($result.Story) | $($result.Result) | $($result.Detail) |")
}
if (@($results).Count -eq 0) {
    [void]$report.AppendLine('| No story-specific artifacts found | - | Current | Nothing to reconcile. |')
}

$report.ToString() | Set-Content -Path $OutputPath -Encoding utf8
Write-Host "Reconciled $(@($results).Count) derived artifacts. Report: '$OutputPath'."