<#
.SYNOPSIS
Generates a manual Mendix Board action checklist from derived artifacts.

.DESCRIPTION
Reads optional board_action metadata under planning. The script never changes
Mendix Epics stories, tasks, sprint assignments, or statuses.
#>

[CmdletBinding()]
param(
    [string]$PlanningDirectory = (Join-Path (Split-Path -Parent $PSScriptRoot) 'planning'),
    [string]$OutputPath = (Join-Path (Split-Path -Parent $PSScriptRoot) 'planning\generated\board-action-report.md')
)

$ErrorActionPreference = 'Stop'

function Get-Frontmatter {
    param([string]$Content)

    $match = [regex]::Match($Content, '(?s)^---\s*\r?\n(.*?)\r?\n---')
    if (-not $match.Success) {
        return $null
    }

    $values = @{}
    foreach ($line in $match.Groups[1].Value -split '\r?\n') {
        if ($line -match '^\s*([^:#]+):\s*(.*?)\s*$') {
            $values[$matches[1].Trim()] = $matches[2].Trim().Trim('"', "'")
        }
    }
    return $values
}

$artifacts = if (Test-Path -Path $PlanningDirectory -PathType Container) {
    Get-ChildItem -Path $PlanningDirectory -Recurse -File -Filter '*.md' |
        Where-Object { $_.FullName -notmatch '[\\/]generated[\\/]' -and $_.FullName -notmatch '[\\/]wave-reports[\\/]' -and $_.Name -notin @('README.md', 'execution-waves.md') }
} else {
    @()
}

$actions = foreach ($artifact in $artifacts) {
    $frontmatter = Get-Frontmatter -Content (Get-Content -Path $artifact.FullName -Raw)
    if ($null -eq $frontmatter) {
        continue
    }

    $action = $frontmatter['board_action']
    if ([string]::IsNullOrWhiteSpace($action) -or $action -eq 'None') {
        continue
    }
    if ([string]::IsNullOrWhiteSpace($frontmatter['board_story'])) {
        continue
    }

    [PSCustomObject]@{
        File = $artifact.FullName
        Story = $frontmatter['board_story']
        State = $frontmatter['state']
        Action = $action
        Evidence = $frontmatter['board_action_evidence']
    }
}

$outputDirectory = Split-Path -Parent $OutputPath
New-Item -ItemType Directory -Force -Path $outputDirectory | Out-Null
$report = [System.Text.StringBuilder]::new()
[void]$report.AppendLine('<!-- Generated by scripts/generate-board-action-report.ps1. Do not edit manually. -->')
[void]$report.AppendLine('# Manual Mendix Board Action Report')
[void]$report.AppendLine()
[void]$report.AppendLine('This is a checklist only. Apply every action manually in the Mendix Epics Board.')
[void]$report.AppendLine()
[void]$report.AppendLine('| Board story | Artifact | Local state | Manual action | Evidence |')
[void]$report.AppendLine('|---|---|---|---|---|')
foreach ($entry in @($actions) | Sort-Object Story, File) {
    $relativeFile = [System.IO.Path]::GetRelativePath((Split-Path -Parent $PSScriptRoot), $entry.File).Replace('\', '/')
    [void]$report.AppendLine("| $($entry.Story) | $relativeFile | $($entry.State) | $($entry.Action) | $($entry.Evidence) |")
}
if (@($actions).Count -eq 0) {
    [void]$report.AppendLine('| - | - | - | No manual Board action is currently requested. | - |')
}

$report.ToString() | Set-Content -Path $OutputPath -Encoding utf8
Write-Host "Reported $(@($actions).Count) manual Board actions. Report: '$OutputPath'."